name: libbulletc-droid

on:
  push:
  workflow_dispatch:
    android_ndk_REV:
      description: android-ndk-REV
      required: false
      default: android-ndk-r23c
    ANDROID_ABI:
      description: ANDROID_ABI
      required: true
      default: arm64-v8a
    ANDROID_PLATFORM:
      description: ANDROID_PLATFORM
      required: true
      default: 31

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: android install NDK
      if: ${{ github.event.inputs.android_ndk_REV != '' && github.event.inputs.android_ndk_REV != 'false' }}
      shell: bash
      run: |
        (
          echo ANDROID_NDK_HOME=$PWD/${{ github.event.inputs.android_ndk_REV }} ;
          echo ANDROID_ABI=$PWD/${{ github.event.inputs.ANDROID_ABI }} ;
          echo ANDROID_PLATFORM=$PWD/${{ github.event.inputs.ANDROID_PLATFORM }} ;
        ) | tee -a $GITHUB_ENV
        dlurl=https://dl.google.com/android/repository/${{ github.event.inputs.android_ndk_REV }}-${RUNNER_OS,,}.zip
        echo "downloading NDK from: $dlurl"
        curl -sL "$dlurl" | unzip

    - uses: actions/checkout@v2

    - name: Install ninja-build tool
      uses: seanmiddleditch/gha-setup-ninja@v3

    - name: fetch bullet
      run: git clone -b 3.24 https://github.com/bulletphysics/bullet3.git

    - name: android generate cmake
      if: ${{ github.event.inputs.android_ndk_REV != '' && github.event.inputs.android_ndk_REV != 'false' }}
      run: |
         cmake -G Ninja . -DANDROID_ABI=${ANDROID_ABI} -DANDROID_PLATFORM=${ANDROID_PLATFORM} \
            -DCMAKE_TOOLCHAIN_FILE=${ANDROID_NDK_HOME}/build/cmake/android.toolchain.cmake \
            -DBULLET_INCLUDE_DIR=$PWD/bullet3

    - name: compile libbulletc
      run: ninja

    - name: Setup .NET Core
      if: false
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      if: false
      run: dotnet restore BulletSharp/BulletSharp.DotNetCore.csproj
    - name: Build
      if: false
      run: dotnet build --configuration Release --no-restore BulletSharp/BulletSharp.DotNetCore.csproj
    - name: Test
      if: false
      run: dotnet test --no-restore --verbosity normal BulletSharp/BulletSharp.DotNetCore.csproj

