name: libbulletc-android

on:
  push:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.runs-on }}
    defaults:
      run:
        shell: bash
    env:
      android_ndk_REV: android-ndk-r23c
      ANDROID_ABI: arm64-v8a
      ANDROID_PLATFORM: 31

    steps:
    - uses: actions/checkout@v2

    - name: android install NDK
      run: |
        (
          echo ANDROID_NDK_HOME=$PWD/${{ env.android_ndk_REV }} ;
          echo ANDROID_ABI=${{ env.ANDROID_ABI }} ;
          echo ANDROID_PLATFORM=${{ env.ANDROID_PLATFORM }} ;
        ) | tee -a $GITHUB_ENV
        dlurl=https://dl.google.com/android/repository/${{ env.android_ndk_REV }}-${RUNNER_OS,,}.zip
        echo "downloading NDK from: $dlurl"
        curl -sL "$dlurl" -o ${android_ndk_REV}.zip
        unzip -qq ${android_ndk_REV}.zip

    - name: Install ninja-build tool
      uses: seanmiddleditch/gha-setup-ninja@v3

    - name: sanity check
      run: |
        ls -l ${ANDROID_NDK_HOME}/build/cmake/android.toolchain.cmake
        cmake --version
        ninja --version

    - name: fetch bullet
      run: git clone --quiet -b 3.24 https://github.com/bulletphysics/bullet3.git

    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v3
    #   with:
    #     limit-access-to-actor: true

    - name: android generate cmake
      run: |
        cd libbulletc
        cmake -G Ninja ../libbulletc -DANDROID_ABI=${ANDROID_ABI} -DANDROID_PLATFORM=${ANDROID_PLATFORM} \
            -DCMAKE_TOOLCHAIN_FILE=${ANDROID_NDK_HOME}/build/cmake/android.toolchain.cmake \
            -DBULLET_INCLUDE_DIR=$PWD/../bullet3/src

    - name: compile libbulletc
      run: ninja -C libbulletc

    - uses: actions/upload-artifact@v3
      with:
        name: libbulletc-${{ env.ANDROID_ABI }}-via-${{ runner.os }}
        path: libbulletc/liblibbulletc.so

    - name: Setup .NET Core
      if: false
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      if: false
      run: dotnet restore BulletSharp/BulletSharp.DotNetCore.csproj
    - name: Build
      if: false
      run: dotnet build --configuration Release --no-restore BulletSharp/BulletSharp.DotNetCore.csproj
    - name: Test
      if: false
      run: dotnet test --no-restore --verbosity normal BulletSharp/BulletSharp.DotNetCore.csproj

